In [1]:
from Decision_Tree import Decision_Tree

0.01 -999999.00
0.04 0.01
0.05 0.04
0.10 0.05
0.12 0.10
0.19 0.12
0.18 0.19
0.26 0.19
0.38 0.26
0.42 0.38
0.45 0.42
0.55 0.45
0.56 0.55
0.50 0.56
0.52 0.56
0.49 0.56
0.46 0.56
0.42 0.56
0.39 0.56
0.36 0.56
0.28 0.56
0.22 0.56
0.18 0.56
0.19 0.56
0.15 0.56
0.14 0.56
0.11 0.56
0.14 0.56
0.12 0.56
0.09 0.56
0.08 0.56
0.07 0.56
0.05 0.56
0.01 0.56
0.01 0.56
0.02 0.56
0.03 0.56
0.06 0.56
0.07 0.56
0.09 0.56
0.13 0.56
0.20 0.56
0.25 0.56
0.26 0.56
0.26 0.56
0.26 0.56
0.28 0.56
0.21 0.56
0.14 0.56
0.11 0.56
0.08 0.56
0.07 0.56
0.04 0.56
0.03 0.56
0.02 0.56
0.01 0.56
0.01 0.56
0.02 0.56
0.04 0.56
0.12 0.56
0.30 0.56
0.53 0.56
0.70 0.56
0.82 0.70
0.92 0.82
0.88 0.92
0.83 0.92
0.79 0.92
0.78 0.92
0.76 0.92
0.75 0.92
0.72 0.92
0.69 0.92
0.68 0.92
0.67 0.92
0.67 0.92
0.67 0.92
0.65 0.92
0.67 0.92
0.72 0.92
0.68 0.92
0.63 0.92
0.58 0.92
0.47 0.92
0.43 0.92
0.40 0.92
0.36 0.92
0.32 0.92
0.23 0.92
0.19 0.92
0.15 0.92
0.12 0.92
0.10 0.92
0.07 0.92
0.05 0.92
0.04 0.92
0.03 0.92
0.01 0.92
0.05 0.92
0.47

In [3]:
import seaborn as sns

In [95]:
class Random_Forest():
    def __init__(self,n_estimators=5,max_depth=5,min_samples_split=2,max_features='sqrt'):
        self.np = __import__('numpy')
        self.num_trees=n_estimators
        self.max_depth= max_depth
        self.max_features= max_features
        self.min_samples_split= min_samples_split
        self.base_model= __import__("Decision_Tree").Decision_Tree
        self.trees= []
    def samples(self,dft):
        temp =dft.iloc[:,[i for i in range(len(dft.columns)) if i!=len(dft.columns)-1]].copy()
        index= self.np.random.choice(temp.index,size=temp.shape[0],replace=True)
        
        if self.max_features=='sqrt':
            number=int(len(temp.columns)**0.5)
        elif self.max_features=='log2':
            number= self.np.log2(len(temp.columns))
        elif self.max_features==None:
            number=len(temp.columns)
        
        cols= self.np.random.choice(temp.columns,size=number)
        return dft.loc[index,cols]
    def fit(self,dft):
        if len(self.trees)>0:
            self.trees=[]
        for _ in range(self.num_trees):
            dft_= Random_Forest().samples(dft)
            model= self.base_model(min_samples=self.min_samples_split,max_depth= self.max_depth)
            print(model)
#             x_=dft.iloc[:,[i for i in range(len(dft.columns)) if i!=len(dft.columns)-1]]
#             y_= dft.iloc[:,-1]
            model.fit(dft_)
            self.trees.append(model)
    def predict(self,x):
        predictions= []
        predict_final=[]
        for mdl in self.trees:
            predictions.append(mdl.predict(x))
        predictions= self.np.transpose(self.np.array(predictions))
        for pr in predictions:
            val,cnt= self.np.unique(pr,return_counts=True)
            predict_final.append(val[self.np.argmax(cnt)])
        return predict_final

In [96]:
rf= Random_Forest()

In [97]:
np.random.choice (df_tr.index,size=10)

array([ 26,  78,  37,  41,  63,  41, 129,  30,  68, 102], dtype=int64)

In [98]:
from sklearn.model_selection import train_test_split
df=sns.load_dataset('iris')
df_tr,df_ts= train_test_split(df,test_size=.3)

In [99]:
x_ts= df_ts.iloc[:,[i for i in range(df_ts.shape[1]) if i!=df_ts.shape[1]-1]]
y_ts= df_ts.iloc[:,-1]

In [ ]:
rf.fit(df_tr)

In [52]:
print(df_tr.index)

Int64Index([134, 117,  45,  81,  86,  52, 147,  85,  54,   8,
            ...
            115,  60,  90,  15,  39,  73, 131,  46,  65, 142],
           dtype='int64', length=105)


In [7]:
from sklearn.metrics import precision_score,f1_score

In [ ]:
precision_score(y_ts,rf.predict(x_ts),average='micro')

In [36]:
df.iloc[:,[i for i in range(len(df.columns)) if i!=len(df.columns)-1]]

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [5]:
import seaborn as sns
d=sns.load_dataset('iris')

In [13]:
y=d['species']

2

In [14]:
import numpy as np

In [45]:
ar= [[1,2,3],[7,8,9],[1,2,3]]
ar=np.transpose(ar)
for i in ar:
    val,cnt=  np.unique(i,return_counts=True)
    print(i)
    print(val[np.argmax(cnt)])

[1 7 1]
1
[2 8 2]
2
[3 9 3]
3


In [61]:
np.log2(8)

3.0

In [32]:
np.transpose(ar).sum(axis=1)

array([ 8, 10, 12])

In [47]:
ar[0]=12